### ISSUE TITLE
Reminder Notfications 

### ISSUE THREAD

**Issue by acmjec** [acmjec/Hacktoberfest_2023-Android_7_Min_Workout#4]
Push Notification reminding the user to do Workout. Define a Set of 3-4 messages and also show one of these messages randomly in content of Notifications.

**Comment by MonuGit9** [comment]
can you assign this to me

**Comment by acmjec** [comment]
Sure @MonuGit9 ! I am Assigning this Issue to You. Start Contributing! Happy Hacking!
